### ISSUE TITLE
Issue with `addCSourceFiles`

### ISSUE THREAD

**Issue by g-berthiaume** [SimonLSchlee/zigraylib#1]
Hi, I'm using zig 0.11.0 and I'm having trouble executing your repo.

```txt
C:\Users\gab\AppData\Local\zig\p\1220ffd2f055bc121bf6ef00cb9df347b5993406efb3a16ac92dd7e6f386ca53f725\src\build.zig:23:11: error: member function expected 2 argument(s), found 1
    raylib.addCSourceFiles(.{
    ~~~~~~^~~~~~~~~~~~~~~~
C:\Users\gab\scoop\apps\zig\current\lib\std\Build\Step\Compile.zig:891:5: note: function declared here
pub fn addCSourceFiles(self: *Compile, files: []const []const u8, flags: []const []const u8) void {
```

Thanks for creating this example !

**Comment by SimonLSchlee** [comment]
Hi @g-berthiaume, this example requires recent development versions of zig I tested with `0.12.0-dev.271+5cc1831ca` and `0.12.0-dev.1773+8a8fd47d2` but installing a master build from https://ziglang.org/download/ should work.

Zig version 0.11.0 is not supported because it doesn't have all the required package manager features, maybe I can create a version for the 0.12.0 version, but judging from this https://github.com/ziglang/zig/milestone/23 the next stable release will still take a while.

So my suggestion would be to try to use master, if you want to stay on 0.11.0 you could give this project a try https://github.com/Not-Nik/raylib-zig which currently uses 0.11.0 and seems to track stable releases of zig.

**Comment by SimonLSchlee** [comment]
@g-berthiaume Closing this issue because 0.11.0 is not supported / too old, see previous comment. If you encounter problems with new zig versions you can create a new issue.

**Comment by g-berthiaume** [comment]
My appologies, I now see that the zig version was specified in the README.
I was assuming that 0.11.0 would be ok.

Thanks again for creating this example.

**Comment by SimonLSchlee** [comment]
You are welcome, did it work for you?
