### ISSUE TITLE
Unable to check cache: stat file

### ISSUE THREAD

**Issue by pattmax00** [SimonLSchlee/zigraylib#2]
Running on the latest version of Zig (0.12.0 dev 3381) yields some strange cache errors. I have cleared zig-cache, re-cloned a fresh project, and I get cache errors no matter what. If you could try compiling with the latest version of Zig master branch and letting me know if it works or not on your system, that would be awesome!

Thanks

**Comment by SimonLSchlee** [comment]
I get the same error with version `0.12.0-dev.3412+54c08579e`, I will try to update raylib to a newer commit and see if that fixes it.

**Comment by pattmax00** [comment]
That sounds good, thanks!

**Comment by SimonLSchlee** [comment]
So I tried with the updated versions and got other errors there, something with the new experimental support for wayland is not quite finished / working.

I ended up adding a single define so that the `build.zig` ends up building X11 support for the raylib build.
Activating Wayland gives me compile errors so I left that out.
The change is a really simple one line define here: https://github.com/SimonLSchlee/raylib/commit/66e2a58b20c81094f9219021ef98fd77189fee92

But I don't quite know whether it should be specified in the `build.zig` like that or whether some other code,
should pick between these options / defaults.

When this is fixed in the raysan5/raylib repo I will switch back to a commit there.

----

@pattmax00 can you test whether the new/latest commit works for you?

It worked for me for zig versions `0.12.0-dev.2618+39ec3d311` and `0.12.0-dev.3412+54c08579e`

If it doesn't work for you, it would be helpful to know on which platform you are compiling and what error you get with the latest version.

**Comment by pattmax00** [comment]
Yes this latest change fixed my issue. I am on Windows 10.
Thanks!
