### ISSUE TITLE
Adding raygui

### ISSUE THREAD

**Issue by nat3Github** [SimonLSchlee/zigraylib#5]
hi, thanks for the example with the zig package manager.
I'm still trying to grog building with build.zig and zon.

I'm trying to use raygui with raylib: 
- added raygui dependency in zon .raygui = .{ .url = "https://github.com/raysan5/raygui/archive/604d2d6ce4dfd072033b2311fd8adaba66654bde.tar.gz", .hash = "1220864a314db60a5e43df335d496c5bbe6ca82c6f2a98e9f34d3c1b00df312a79a3" }
- included the raylib.h in the build.zig so we can include raygui header with @cInclude("raygui.h")
- added     @cDefine("RAYGUI_IMPLEMENTATION", {});    @cInclude("raygui.h"); in raylib.zig
- the urls are from respective master branches of raylib/ raygui (as of 07-23-24)

problem:  error: expected type 'usize', found '[*c]u8'
                    fileDataPtr += @as([*c]u8, @ptrFromInt(@sizeOf(c_int)));
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
referenced by:
    GuiLoadStyle: D:\Programming\Zig\prototyping\zigraylib\.zig-cache\o\979fb58a68b8bcdd14106ae1ed3f8091\cimport.zig:5441:17

Do you have a hunch where this error may be coming from?

I'd love to add raygui to this repository as it would potentially benefit other users as well.
thanks in advance!

**Comment by SimonLSchlee** [comment]
> Do you have a hunch where this error may be coming from?

It is the error described here (bottom half): https://ziggit.dev/t/using-raygui-with-raylib/3399/7?u=sze

Note that the raylib `build.zig` already has support for raygui:
https://github.com/raysan5/raylib/blob/30f9ca7eb60d527e623066bbdc7257474da2baef/src/build.zig#L251

However I don't think it has something to deal with the cImport/c-translate issue, creating a wrong translation.
I think one approach to solving that could be to experiment whether the c-code can be written in a different style,
that gets correctly translated and still is good c code, if somebody could come up with such c code, then maybe raylib would take that change as a pull request, which would solve the issue for raygui+zig users.

One alternative might be to use c-translate instead of cImport and then apply a patch file to resulting source code.

Yet another thing could be to figure out whether this is something that could/should be handled by c-translate and whether there is some fix to c-translate that would change it to translate the code correctly.

> I'd love to add raygui to this repository as it would potentially benefit other users as well.
thanks in advance!

I am open to adding it, but because using raygui is a bit messy currently, I would keep it in a raygui branch and link to it from the readme, until it becomes less messy.

I currently can't dedicate a lot of time to things I don't use directly, so I would help, but would want somebody who helps with maintanance / keeping up to date with raygui related things.

**Comment by SimonLSchlee** [comment]
Yet another approach might be to create a zig file that has the extern function and type declarations only and then compile raygui as a c source file for the actual implementations, that way the implementation part wouldn't have to go through the translate-c, which avoids the error. But I don't know how to do that in a practical sense, theoretically it makes sense, but in practice it might be annoying manual work.

I had another look at https://github.com/raysan5/raylib/blob/30f9ca7eb60d527e623066bbdc7257474da2baef/src/build.zig#L239 I think it avoids the whole translate-c issue exactly by treating the raygui code as a c source file.
So I think that is the way to go.

**Comment by SimonLSchlee** [comment]
Reading the more recent code related to raygui in raylib's `build.zig`, is making me think that maybe it is now at a point where raygui isn't messy to use anymore.

**Comment by SimonLSchlee** [comment]
@nat3Github If you checkout the branch https://github.com/SimonLSchlee/zigraylib/tree/raygui that is a working raygui example.

Because it turns out to be easier than I thought, I will add it and maintain it, I am still not completely sure whether I will add it to the main branch or keep it in raygui branch, I will think about it for a bit.

I also think the example should use it for something that demonstrates it a bit.

Thank you for your suggestion!

It made me realize it is easier than I thought, I think the last time I looked at it the raylib `build.zig` wasn't as easy to use, or maybe my understanding has improved in the meantime.

**Comment by nat3Github** [comment]
thank you so much!

> However I don't think it has something to deal with the cImport/c-translate issue, creating a wrong translation.

I guess I was expecting the C interop to be on C++ level :(. Maybe this gets tackled after the core team finished the compiler related stuff. I'm crossing my fingers!

> I had another look at https://github.com/raysan5/raylib/blob/30f9ca7eb60d527e623066bbdc7257474da2baef/src/build.zig#L239 I think it avoids the whole translate-c issue exactly by treating the raygui code as a c source file. So I think that is the way to go.

while zigs c-translate is incomplete I get that it's better to have definition only header files and implementation c/cpp files.
with raylib.h the current solution is great as the header is also a header without the implementations with the macro not beeing defined.
